service: dat-song-bot

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'production'}
  region: ap-south-1
  environment:
    NODE_ENV: ${opt:stage, 'production'}
    YOUTUBE_CLIENT_ID: ${ssm:YOUTUBE_CLIENT_ID}
    YOUTUBE_CLIENT_SECRET: ${ssm:YOUTUBE_CLIENT_SECRET~true}
    YOUTUBE_REFRESH_TOKEN: ${ssm:YOUTUBE_REFRESH_TOKEN~true}
    SOUNDCLOUD_CLIENT_ID: ${ssm:SOUNDCLOUD_CLIENT_ID}
    UNSPLASH_ACCESS_KEY: ${ssm:UNSPLASH_ACCESS_KEY}
    DEBUG: '*Logger'
    SENTRY_DSN: ${ssm:SENTRY_DSN}

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/** # exclude puppeteer chrome if exists
    - test

custom:
  webpack:
    packager: 'yarn'
    forceInclude:
      - '@ffmpeg-installer/ffmpeg'

functions:
  dat-song-bot:
    name: dat-song-bot-${self:provider.stage}
    description: 'This function generates and uploads a video to youtube!'
    memorySize: 3008
    timeout: 900 # 15 minutes
    handler: src/index.main
