version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.9-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:10.9
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn release
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
