import { Track } from '../../src/audio';
import { IUnsplashResponse } from '../../src/image';

export const tracks: Partial<Track>[] = [
  {
    comment_count: 0,
    downloadable: false,
    release: null,
    created_at: '2019/06/21 18:53:15 +0000',
    description:
      'Just Hebrew words that have been downloaded individually from Forvo that i would like to share with anyone who is interested in language learning.',
    original_content_size: 37054,
    title: 'Wave He גל',
    track_type: null,
    duration: 443,
    video_url: null,
    original_format: 'wav',
    artwork_url: null,
    streamable: true,
    tag_list: '',
    release_month: 6,
    genre: '',
    release_day: 21,
    id: 640194939,
    state: 'finished',
    reposts_count: 0,
    last_modified: '2019/06/21 18:53:15 +0000',
    label_name: null,
    commentable: true,
    bpm: null,
    policy: 'ALLOW',
    favoritings_count: 0,
    kind: 'track',
    purchase_url: null,
    release_year: 2019,
    key_signature: null,
    isrc: null,
    sharing: 'public',
    uri: 'https://api.soundcloud.com/tracks/640194939',
    attachments_uri: 'https://api.soundcloud.com/tracks/640194939/attachments',
    download_count: 0,
    likes_count: 0,
    license: 'all-rights-reserved',
    purchase_title: null,
    user_id: 655787799,
    embeddable_by: 'all',
    monetization_model: 'NOT_APPLICABLE',
    waveform_url: 'https://w1.sndcdn.com/SDZIqtuwu6I1_m.png',
    permalink: 'wave-he',
    permalink_url: 'http://soundcloud.com/user-525309592/wave-he',
    user: {
      id: 655787799,
      kind: 'user',
      permalink: 'user-525309592',
      username: 'Matthew186f',
      last_modified: '2019/06/21 18:52:21 +0000',
      uri: 'https://api.soundcloud.com/users/655787799',
      permalink_url: 'http://soundcloud.com/user-525309592',
      avatar_url: 'https://a1.sndcdn.com/images/default_avatar_large.png',
    },
    label_id: null,
    stream_url: 'https://api.soundcloud.com/tracks/640194939/stream',
    playback_count: 0,
  },
  {
    comment_count: 0,
    downloadable: false,
    release: null,
    created_at: '2019/06/21 18:53:15 +0000',
    description: '',
    original_content_size: 54780320,
    title:
      'Sech X Darell X Deejay C - Otro Trago Reggaeton Break Acapella 92 - Bpm',
    track_type: null,
    duration: 207090,
    video_url: null,
    original_format: 'wav',
    artwork_url: null,
    streamable: true,
    tag_list: '',
    release_month: null,
    genre: 'Reggaeton',
    release_day: null,
    id: 640194936,
    state: 'finished',
    reposts_count: 0,
    last_modified: '2019/06/21 18:53:15 +0000',
    label_name: null,
    commentable: true,
    bpm: null,
    policy: 'ALLOW',
    favoritings_count: 0,
    kind: 'track',
    purchase_url: null,
    release_year: null,
    key_signature: null,
    isrc: null,
    sharing: 'public',
    uri: 'https://api.soundcloud.com/tracks/640194936',
    attachments_uri: 'https://api.soundcloud.com/tracks/640194936/attachments',
    download_count: 0,
    likes_count: 0,
    license: 'all-rights-reserved',
    purchase_title: null,
    user_id: 326158808,
    embeddable_by: 'all',
    monetization_model: 'NOT_APPLICABLE',
    waveform_url: 'https://w1.sndcdn.com/ehCM78P1YDxa_m.png',
    permalink:
      'sech-x-darell-x-deejay-c-otro-trago-reggaeton-break-acapella-92-bpm',
    permalink_url:
      'http://soundcloud.com/user-634648612/sech-x-darell-x-deejay-c-otro-trago-reggaeton-break-acapella-92-bpm',
    user: {
      id: 326158808,
      kind: 'user',
      permalink: 'user-634648612',
      username: 'DEEJAY C',
      last_modified: '2019/01/06 12:23:49 +0000',
      uri: 'https://api.soundcloud.com/users/326158808',
      permalink_url: 'http://soundcloud.com/user-634648612',
      avatar_url: 'https://i1.sndcdn.com/avatars-000559419753-tdadbv-large.jpg',
    },
    label_id: null,
    stream_url: 'https://api.soundcloud.com/tracks/640194936/stream',
    playback_count: 0,
  },
  {
    comment_count: 0,
    downloadable: false,
    release: null,
    created_at: '2019/06/21 18:53:14 +0000',
    description: '',
    original_content_size: 41278778,
    title: 'Dark Dayz',
    track_type: null,
    duration: 156096,
    video_url: null,
    original_format: 'wav',
    artwork_url: null,
    streamable: true,
    tag_list: 'Beats beatsforsale typebeat Trap Rap "Hip Hop"',
    release_month: null,
    genre: '',
    release_day: null,
    id: 640194933,
    state: 'finished',
    reposts_count: 0,
    last_modified: '2019/06/21 18:53:14 +0000',
    label_name: null,
    commentable: true,
    bpm: null,
    policy: 'ALLOW',
    favoritings_count: 0,
    kind: 'track',
    purchase_url: null,
    release_year: null,
    key_signature: null,
    isrc: null,
    sharing: 'public',
    uri: 'https://api.soundcloud.com/tracks/640194933',
    attachments_uri: 'https://api.soundcloud.com/tracks/640194933/attachments',
    download_count: 0,
    likes_count: 0,
    license: 'all-rights-reserved',
    purchase_title: null,
    user_id: 171477925,
    embeddable_by: 'all',
    monetization_model: 'NOT_APPLICABLE',
    waveform_url: 'https://w1.sndcdn.com/pCfKSpyMqUmI_m.png',
    permalink: 'dark-dayz',
    permalink_url: 'http://soundcloud.com/royalonthebeat/dark-dayz',
    user: {
      id: 171477925,
      kind: 'user',
      permalink: 'royalonthebeat',
      username: 'royal',
      last_modified: '2019/06/10 11:57:58 +0000',
      uri: 'https://api.soundcloud.com/users/171477925',
      permalink_url: 'http://soundcloud.com/royalonthebeat',
      avatar_url: 'https://i1.sndcdn.com/avatars-000563318574-7oazne-large.jpg',
    },
    label_id: null,
    stream_url: 'https://api.soundcloud.com/tracks/640194933/stream',
    playback_count: 0,
  },
];

export const imageData: IUnsplashResponse = {
  id: 'nKEARsgmrqc',
  created_at: '2018-02-12T12:52:30-05:00',
  updated_at: '2019-06-07T01:05:15-04:00',
  width: 4240,
  height: 2832,
  color: '#E9D7AA',
  description: 'FREE YOUR MIND \u2026 READ',
  urls: {
    raw:
      'https://images.unsplash.com/photo-1518457900604-5c973dffdedf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjc2NjkzfQ',
    full:
      'https://images.unsplash.com/photo-1518457900604-5c973dffdedf?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjc2NjkzfQ',
    regular:
      'https://images.unsplash.com/photo-1518457900604-5c973dffdedf?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjc2NjkzfQ',
    small:
      'https://images.unsplash.com/photo-1518457900604-5c973dffdedf?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjc2NjkzfQ',
    thumb:
      'https://images.unsplash.com/photo-1518457900604-5c973dffdedf?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjc2NjkzfQ',
    custom:
      'https://images.unsplash.com/photo-1518457900604-5c973dffdedf?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1920&h=1080&fit=crop&ixid=eyJhcHBfaWQiOjc2NjkzfQ',
  },
  links: {
    self: 'https://api.unsplash.com/photos/nKEARsgmrqc',
    html: 'https://unsplash.com/photos/nKEARsgmrqc',
    download: 'https://unsplash.com/photos/nKEARsgmrqc/download',
    download_location: 'https://api.unsplash.com/photos/nKEARsgmrqc/download',
  },
  likes: 89,
  liked_by_user: false,
  user: {
    id: 'HYML7xMkVco',
    updated_at: '2019-06-15T21:03:27-04:00',
    username: 'lordmaui',
    name: 'Chris Benson',
    twitter_username: null,
    portfolio_url: 'http://hyperurl.co/3VMBiscayne',
    bio:
      'If you\u2019re downloading my work make sure you like it at least lol  and it would be dope to get a link to where the pictures helped you achieve whatever you\u2019re  doing ..   email pakercenter08@gmail.com click the link in bio  support me please share .!',
    location: 'Fort Wayne ind ',
    links: {
      self: 'https://api.unsplash.com/users/lordmaui',
      html: 'https://unsplash.com/@lordmaui',
      photos: 'https://api.unsplash.com/users/lordmaui/photos',
      likes: 'https://api.unsplash.com/users/lordmaui/likes',
      portfolio: 'https://api.unsplash.com/users/lordmaui/portfolio',
    },
    instagram_username: 'lordmaui1.5',
    total_collections: 0,
    total_likes: 412,
    total_photos: 194,
  },
  downloads: 8563,
};
